--- CREAR LA BASE DE DATOS
IF EXISTS(SELECT * FROM DBO.SYSDATABASES WHERE NAME = 'BDFASTFOOD') 
	BEGIN
		USE NORTHWIND
		DROP DATABASE BDFASTFOOD
	END 
	CREATE DATABASE BDFASTFOOD
	GO
	USE BDFASTFOOD

--- CREAR LA TABLA USUARIO
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME = 'USUARIO')
      DROP TABLE USUARIO
CREATE TABLE USUARIO
(
USR_ID CHAR(5) NOT NULL PRIMARY KEY,
USR_NOMBRE VARCHAR(100) NOT NULL,
USR_APELLIDO VARCHAR(100) NOT NULL,
USR_CLAVE VARCHAR(20) NOT NULL,
USR_ESTADO CHAR(1)
)

--- CREAR LA TABLA CATEGORIA
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME = 'CATEGORIA')
      DROP TABLE CATEGORIA
CREATE TABLE CATEGORIA
(
CAT_ID CHAR(2) NOT NULL PRIMARY KEY,
CAT_DESCRIPCION VARCHAR(100) NOT NULL,
CAT_ORDEN INT,
CAT_ESTADO CHAR(1)
)

--- CREAR LA TABLA PRODUCTO
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME = 'PRODUCTO')
      DROP TABLE PRODUCTO
CREATE TABLE PRODUCTO
(
PROD_ID CHAR(4) NOT NULL PRIMARY KEY,
PROD_DESCRIPCION VARCHAR(200) NOT NULL,
PROD_DESC_CORTA VARCHAR(100) NOT NULL,
PROD_PRECIO NUMERIC(10,2),
PROD_STOCK NUMERIC(5),
PROD_ESTADO CHAR(1) NOT NULL,
CAT_ID CHAR(2) NOT NULL
)

--- CREAR LA TABLA PEDIDO
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME = 'PEDIDO')
      DROP TABLE PEDIDO
CREATE TABLE PEDIDO
(
PED_ID CHAR(8) NOT NULL PRIMARY KEY,
PED_FECHA DATE NOT NULL,
PED_CLIENTE VARCHAR(255),
USR_ID CHAR(5) NOT NULL,
PED_ESTADO CHAR(1) NOT NULL
)

--- CREAR LA TABLA DETPEDIDO
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME = 'DETPEDIDO')
      DROP TABLE DETPEDIDO
CREATE TABLE DETPEDIDO
(
DET_ITEM INT NOT NULL,
PED_ID CHAR(8) NOT NULL,
PROD_ID CHAR(4) NOT NULL,
DET_CANTIDAD NUMERIC(5) NOT NULL,
DET_PRECIO NUMERIC(10,2)
)

ALTER TABLE DETPEDIDO ADD PRIMARY KEY(DET_ITEM,PED_ID,PROD_ID)

--- REGISTRO DE USUARIOS
INSERT INTO USUARIO (USR_ID, USR_NOMBRE, USR_APELLIDO, USR_CLAVE, USR_ESTADO) VALUES ('16001','JUAN','PEREZ','09090909','A')
SELECT * FROM USUARIO
--- REGISTRO DE CATEGORIAS
INSERT INTO CATEGORIA (CAT_ID,CAT_DESCRIPCION,CAT_ORDEN,CAT_ESTADO) VALUES ('01','BEBIDAS',1,'A')
INSERT INTO CATEGORIA (CAT_ID,CAT_DESCRIPCION,CAT_ORDEN,CAT_ESTADO) VALUES ('02','SANDWICH',2,'A')
INSERT INTO CATEGORIA (CAT_ID,CAT_DESCRIPCION,CAT_ORDEN,CAT_ESTADO) VALUES ('03','HELADOS',3,'A')
INSERT INTO CATEGORIA (CAT_ID,CAT_DESCRIPCION,CAT_ORDEN,CAT_ESTADO) VALUES ('04','DULCES',4,'A')
SELECT * FROM CATEGORIA
--- REGISTRO DE PRODUCTOS
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0001','COCA COLA 500 ml','COCA 500',3.5,100,'A','01')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0002','INCA KOLA 500 ml','INKE 500',3.5,100,'A','01')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0003','FANTA 500 ml','FANTA 500',3,50,'A','01')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0004','SPRITE 500 ml','SPRITE 500',3,50,'A','01')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0005','AGUA SAN MATEO','SN. MATEO 500',2.5,100,'A','01')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0006','SANDWICH TRIPLE','SAND. TRIPLE',3.5,20,'A','02')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0007','HAMBURGUESA DE POLLO','HAMB. POLLO',4,50,'A','02')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0008','HAMBURGUESA DE CARNE','HAMB. CARNE',4,50,'A','02')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0009','HAMBURGUESA ROYAL','HAMB. ROYAL',6,50,'A','02')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0010','SANDWICH DE JAMON','SAND. JAMON',8,50,'A','02')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0011','SANDWICH DE PAVO','SAND. PAVO',8,50,'A','02')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0012','HELADOS SIMPLE','HLD. SIMPLE',5,50,'A','03')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0013','HELADOS DOBLE','HLD. DOBLE',8,50,'A','03')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0014','HELADOS TRIPLE','HLD. TRIPLE',11,50,'A','03')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0015','HELADOS TRIPLE','HLD. TRIPLE',11,50,'A','03')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0016','LECHE ASADA','LECHE ASADA',3,50,'A','04')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0017','GELATINA','GELATINA',2,50,'A','04')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0018','FLAN','FLAN',3,50,'A','04')
INSERT INTO PRODUCTO(PROD_ID,PROD_DESCRIPCION, PROD_DESC_CORTA,PROD_PRECIO,PROD_STOCK,PROD_ESTADO,CAT_ID) VALUES ('0019','TORTA HELADA','TORTA HELADA',4,50,'A','04')
SELECT * FROM PRODUCTO

--- =============================================================================================
--- CREAR PROCEDIMIENTO ALMACENADO SP_CONSULTA_CATEGORIA
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='P' AND NAME = 'SP_CONSULTA_CATEGORIA')
      DROP PROCEDURE SP_CONSULTA_CATEGORIA
GO
CREATE PROCEDURE SP_CONSULTA_CATEGORIA
@TIPO CHAR(1),  
@CAT_ID CHAR(2)
AS
IF @TIPO='N' 
	SELECT CASE WHEN MAX(CAT_ID)>0 THEN CONVERT(INT,MAX(CAT_ID))+1 ELSE 1 END AS NUEVO_ID FROM CATEGORIA
	IF @TIPO='B'
		SELECT * FROM CATEGORIA WHERE CAT_ID=@CAT_ID
	ELSE
		SELECT * FROM CATEGORIA

--- EJECUTAR PROCEDIMIENTO ALMACENADO SP_CONSULTA_CATEGORIA
EXECUTE SP_CONSULTA_CATEGORIA 'N',''

--- =============================================================================================
--- CREAR PROCEDIMIENTO ALMACENADO SP_MANT_CATEGORIA
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='P' AND NAME = 'SP_MANT_CATEGORIA')
      DROP PROCEDURE SP_MANT_CATEGORIA
GO
CREATE PROCEDURE SP_MANT_CATEGORIA
@TIPO CHAR(1), 
@CAT_ID CHAR(2),
@CAT_DESCRIPCION VARCHAR(100),
@CAT_ORDEN INT,
@CAT_ESTADO CHAR(1)
AS
IF @TIPO='I'
	INSERT INTO CATEGORIA (CAT_ID,CAT_DESCRIPCION,CAT_ORDEN,CAT_ESTADO) VALUES (@CAT_ID,@CAT_DESCRIPCION,@CAT_ORDEN,@CAT_ESTADO)
ELSE
	IF @TIPO='U'
		UPDATE CATEGORIA SET CAT_DESCRIPCION=@CAT_DESCRIPCION, CAT_ORDEN=@CAT_ORDEN, CAT_ESTADO=@CAT_ESTADO WHERE CAT_ID=@CAT_ID
	ELSE
		DELETE FROM CATEGORIA WHERE CAT_ID=@CAT_ID

--- EJECUTAR PROCEDIMIENTO ALMACENADO SP_MANT_CATEGORIA
EXECUTE SP_MANT_CATEGORIA 'U','03','wwwww',10,'A'

